In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
import pandas as pd

# File paths
collections_file = '/kaggle/input/ai-governance-documents-data/agora/collections.csv'
documents_file = '/kaggle/input/ai-governance-documents-data/agora/documents.csv'
segments_file = '/kaggle/input/ai-governance-documents-data/agora/segments.csv'
authorities_file = '/kaggle/input/ai-governance-documents-data/agora/authorities.csv'

# Read CSV files
collections_df = pd.read_csv(collections_file)
documents_df = pd.read_csv(documents_file)
segments_df = pd.read_csv(segments_file)
authorities_df = pd.read_csv(authorities_file)

# Display the first few rows of one DataFrame
print(collections_df.head())


FileNotFoundError: [Errno 2] No such file or directory: '/kaggle/input/ai-governance-documents-data/agora/collections.csv'

In [8]:
from pathlib import Path

# Directory containing text files
text_dir = Path('/kaggle/input/ai-governance-documents-data/agora/fulltext/')

# Read all text files
text_files = text_dir.glob('*.txt')  # Get all .txt files
for file in text_files:
    with open(file, 'r') as f:
        content = f.read()
        print(f"Contents of {file.name}:\n{content[:200]}...\n")  # Print the first 200 characters


Contents of 1356.txt:
September 24, 2024

M-24-18

MEMORANDUM FOR THE HEADS OF EXECUTIVE DEPARTMENTS AND AGENCIES
FROM:	Shalanda D. Young	 
SUBJECT:	Advancing the Responsible Acquisition of Artificial Intelligence in Gover...

Contents of 557.txt:
H. R. 6571


IN THE SENATE OF THE UNITED STATES


May 16, 2024


Received; read twice and referred to the Committee on Commerce, Science, and Transportation


AN ACT
To establish a critical supply cha...

Contents of 1721.txt:
    Section 30. The Managed Care Reform and Patient Rights Act
is amended by changing Sections 10, 45, and 85 as follows:
 
    (215 ILCS 134/10)
    Sec. 10. Definitions. In this Act:
    For a healt...

Contents of 1025.txt:
A. Impact on Examination Procedure and Prior Examination Guidance
While this guidance is focused on AI-assisted inventions, portions of the guidance can apply to other types of inventions. To the exte...

Contents of 655.txt:
SECTION 1. SHORT TITLE.
This Act may be cited as the “National Mesonet A

In [9]:
collections_df.info()  # Check for missing values or data types

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Name         10 non-null     object
 1   Description  10 non-null     object
dtypes: object(2)
memory usage: 288.0+ bytes


In [10]:
from pathlib import Path

# Directory containing text files
text_dir = Path('/kaggle/input/ai-governance-documents-data/agora/fulltext/')

# Get all .txt files
text_files = list(text_dir.glob('*.txt'))

# Print properties of each text file
for file in text_files:
    # File size
    file_size = file.stat().st_size  # Size in bytes
    # Read the content to check number of lines and characters
    with open(file, 'r') as f:
        content = f.read()
        num_lines = len(content.split('\n'))
        num_chars = len(content)
    
    print(f"Properties of {file.name}:")
    print(f"Size: {file_size / 1024:.2f} KB")
    print(f"Number of lines: {num_lines}")
    print(f"Number of characters: {num_chars}")
    print('-' * 40)


Properties of 1356.txt:
Size: 83.16 KB
Number of lines: 431
Number of characters: 84885
----------------------------------------
Properties of 557.txt:
Size: 38.96 KB
Number of lines: 817
Number of characters: 39574
----------------------------------------
Properties of 1721.txt:
Size: 21.31 KB
Number of lines: 403
Number of characters: 21823
----------------------------------------
Properties of 1025.txt:
Size: 33.57 KB
Number of lines: 46
Number of characters: 34141
----------------------------------------
Properties of 655.txt:
Size: 9.27 KB
Number of lines: 43
Number of characters: 9345
----------------------------------------
Properties of 788.txt:
Size: 8.09 KB
Number of lines: 149
Number of characters: 8257
----------------------------------------
Properties of 141.txt:
Size: 4.15 KB
Number of lines: 25
Number of characters: 4176
----------------------------------------
Properties of 1009.txt:
Size: 9.27 KB
Number of lines: 53
Number of characters: 9364
-------------------------

In [11]:
import pandas as pd
import numpy as np

# Read the documents CSV file (or any other CSV file you'd like to work with)
documents_df = pd.read_csv('/kaggle/input/ai-governance-documents-data/agora/documents.csv')

# Let's assume we only want the numeric columns for matrix operations
numeric_df = documents_df.select_dtypes(include=[np.number])

# Step 1: Transpose of the matrix
transposed_matrix = numeric_df.T  # Transpose using pandas

# Step 2: Inversion of the matrix (only possible if it's square and invertible)
if numeric_df.shape[0] == numeric_df.shape[1]:
    try:
        inverted_matrix = np.linalg.inv(numeric_df.values)  # Inverse using numpy
        print("Inverse of the matrix:")
        print(inverted_matrix)
    except np.linalg.LinAlgError:
        print("Matrix is not invertible.")
else:
    print("Matrix is not square, cannot compute inversion.")

# Step 3: Dot product of the matrix and its transpose
dot_product = np.dot(numeric_df.values, transposed_matrix.values)  # Dot product using numpy

# Displaying the results
print("\nTranspose of the matrix:")
print(transposed_matrix.head())  # Display the transpose (first 5 rows)

print("\nDot product of the matrix and its transpose:")
print(dot_product)


Matrix is not square, cannot compute inversion.

Transpose of the matrix:
                            0     1     2    3    4     5     6     7     8    \
AGORA ID                    444  1723  1721  281  175  1076  1088  1152  1543   
Number of segments created   23    28    17   14    9     8     9     7     7   

                             9    ...  640  641  642  643  644  645  646  647  \
AGORA ID                    1726  ...  164  165  211  212  213  214  215  216   
Number of segments created     7  ...    9    2    2    3    3    4    6    3   

                            648  649  
AGORA ID                    217  218  
Number of segments created    1    1  

[2 rows x 650 columns]

Dot product of the matrix and its transpose:
[[ 197665  765656  764515 ...   95973   96371   96815]
 [ 765656 2969513 2965759 ...  372252  373919  375642]
 [ 764515 2965759 2962130 ...  371787  373474  375195]
 ...
 [  95973  372252  371787 ...   46665   46875   47091]
 [  96371  373919  373474 

In [12]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Read the CSV files (choose one file or multiple)
collections_df = pd.read_csv('/kaggle/input/ai-governance-documents-data/agora/collections.csv')
documents_df = pd.read_csv('/kaggle/input/ai-governance-documents-data/agora/documents.csv')
segments_df = pd.read_csv('/kaggle/input/ai-governance-documents-data/agora/segments.csv')
authorities_df = pd.read_csv('/kaggle/input/ai-governance-documents-data/agora/authorities.csv')

# Create a directory to save the plots
save_dir = '/kaggle/working/plots/'
import os
if not os.path.exists(save_dir):
    os.makedirs(save_dir)

# --- Line Graph (Example: Plotting a column over time or order) ---
def plot_line_graph(df, column):
    plt.figure(figsize=(10, 6))
    plt.plot(df[column], label=column)
    plt.title(f'Line Graph of {column}')
    plt.xlabel('Index')
    plt.ylabel(column)
    plt.legend()
    plt.grid(True)
    # Save to disk
    plt.savefig(save_dir + f'line_graph_{column}.png')
    plt.show()

# Example: Plotting 'some_column' from documents_df (replace with an actual numeric column name)
# plot_line_graph(documents_df, 'some_column')  # Uncomment and replace with actual column

# --- Bar Graph (Example: Categorical data count) ---
def plot_bar_graph(df, column):
    plt.figure(figsize=(10, 6))
    sns.countplot(x=column, data=df)
    plt.title(f'Bar Graph of {column}')
    plt.xlabel(column)
    plt.ylabel('Count')
    plt.xticks(rotation=45)
    # Save to disk
    plt.savefig(save_dir + f'bar_graph_{column}.png')
    plt.show()

# Example: Plotting 'some_category_column' (replace with an actual categorical column name)
# plot_bar_graph(documents_df, 'some_category_column')  # Uncomment and replace with actual column

# --- Histogram (Example: Distribution of a numerical column) ---
def plot_histogram(df, column):
    plt.figure(figsize=(10, 6))
    plt.hist(df[column], bins=20, color='skyblue', edgecolor='black')
    plt.title(f'Histogram of {column}')
    plt.xlabel(column)
    plt.ylabel('Frequency')
    # Save to disk
    plt.savefig(save_dir + f'histogram_{column}.png')
    plt.show()

# Example: Plotting the distribution of a numerical column like 'numeric_column'
# plot_histogram(documents_df, 'numeric_column')  # Uncomment and replace with actual column

# --- Pie Chart (Example: Proportions of a categorical column) ---
def plot_pie_chart(df, column):
    plt.figure(figsize=(8, 8))
    df[column].value_counts().plot(kind='pie', autopct='%1.1f%%', startangle=90, colors=sns.color_palette('Set3', len(df[column].unique())))
    plt.title(f'Pie Chart of {column}')
    # Save to disk
    plt.savefig(save_dir + f'pie_chart_{column}.png')
    plt.show()

# Example: Plotting a pie chart of 'category_column' (replace with actual categorical column name)
# plot_pie_chart(documents_df, 'category_column')  # Uncomment and replace with actual column

# --- Scatter Plot (Example: Relationship between two numerical columns) ---
def plot_scatter_plot(df, column_x, column_y):
    plt.figure(figsize=(10, 6))
    plt.scatter(df[column_x], df[column_y], alpha=0.6)
    plt.title(f'Scatter Plot: {column_x} vs {column_y}')
    plt.xlabel(column_x)
    plt.ylabel(column_y)
    # Save to disk
    plt.savefig(save_dir + f'scatter_plot_{column_x}_vs_{column_y}.png')
    plt.show()

# Example: Plotting relationship between 'numeric_column1' and 'numeric_column2'
# plot_scatter_plot(documents_df, 'numeric_column1', 'numeric_column2')  # Uncomment and replace with actual columns


In [14]:
import pickle

# Save the dataframe as a pickle file
with open('/kaggle/working/collections_df.pkl', 'wb') as f:
    pickle.dump(collections_df, f)


In [15]:
# Load the dataframe from the pickle file
with open('/kaggle/working/collections_df.pkl', 'rb') as f:
    loaded_collections_df = pickle.load(f)

print(loaded_collections_df.head())


                        Name  \
0              Multinational   
1  Enacted laws and policies   
2             Editors' Picks   
3  U.S. state and local laws   
4    Miscellaneous documents   

                                         Description  
0  Notable AI governance documents from multinati...  
1  All AGORA governmental documents that have bee...  
2  Notable AI governance documents from the U.S. ...  
3  AI-related laws from U.S. states and localitie...  
4        Documents not covered in other collections.  


In [16]:
# Save the dataframe as an HDF5 file
collections_df.to_hdf('/kaggle/working/collections_df.h5', key='df', mode='w')


In [ ]:
# Load the dataframe from the HDF5 file
loaded_collections_df_h5 = pd.read_hdf('/kaggle/working/collections_df.h5', 'df')

print(loaded_collections_df_h5.head())


In [ ]:
import zipfile
import os

# Create a ZIP file and add data files to it
with zipfile.ZipFile('/kaggle/working/collections_data.zip', 'w') as zipf:
    zipf.write('/kaggle/input/ai-governance-documents-data/agora/collections.csv', 'collections.csv')
    zipf.write('/kaggle/input/ai-governance-documents-data/agora/documents.csv', 'documents.csv')


In [ ]:
# Extract the files from the ZIP archive
with zipfile.ZipFile('/kaggle/working/collections_data.zip', 'r') as zipf:
    zipf.extractall('/kaggle/working/')

# Load the extracted CSV files
extracted_collections_df = pd.read_csv('/kaggle/working/collections.csv')
extracted_documents_df = pd.read_csv('/kaggle/working/documents.csv')

print(extracted_collections_df.head())


In [ ]:
import sqlite3

# Create a SQLite database and save the dataframe
conn = sqlite3.connect('/kaggle/working/collections_data.db')
collections_df.to_sql('collections', conn, if_exists='replace', index=False)
conn.close()


In [ ]:
# Reload the data from the SQLite database
conn = sqlite3.connect('/kaggle/working/collections_data.db')
loaded_collections_df_sql = pd.read_sql('SELECT * FROM collections', conn)
conn.close()

print(loaded_collections_df_sql.head())


In [ ]:
import scipy.io

# Save the dataframe as a MATLAB .mat file
scipy.io.savemat('/kaggle/working/collections_df.mat', {'collections': collections_df.to_dict()})


In [17]:
# Reload the data from the .mat file
loaded_collections_df_mat = scipy.io.loadmat('/kaggle/working/collections_df.mat')
# Extract the collections data
collections_data = loaded_collections_df_mat['collections']

# Convert back to DataFrame
collections_df_mat = pd.DataFrame.from_dict(collections_data)
print(collections_df_mat.head())


NameError: name 'scipy' is not defined

In [18]:
# Save multiple arrays into a compressed NPZ file
np.savez('/kaggle/working/collections_data.npz', collections=collections_np, documents=documents_df.to_numpy())


NameError: name 'collections_np' is not defined

In [19]:
# Load multiple arrays from the NPZ file
loaded_npz = np.load('/kaggle/working/collections_data.npz')
collections_array = loaded_npz['collections']
documents_array = loaded_npz['documents']

print(collections_array[:5])  # Display first 5 rows


FileNotFoundError: [Errno 2] No such file or directory: '/kaggle/working/collections_data.npz'